<?php

return [
    'Italian' => [
        ['name' => 'Spaghetti alla Carbonara', 'price' => 12.99, 'description' => 'Classic Italian pasta dish with eggs, cheese, pancetta, and pepper.'],
        ['name' => 'Margherita Pizza', 'price' => 10.99, 'description' => 'Traditional Neapolitan pizza topped with tomato sauce, mozzarella, and basil.'],
        ['name' => 'Risotto ai Funghi', 'price' => 15.99, 'description' => 'Creamy risotto cooked with mushrooms, onions, and white wine.'],
        ['name' => 'Lasagna', 'price' => 14.99, 'description' => 'Layered pasta dish with Bolognese sauce, béchamel, and cheese.'],
        ['name' => 'Osso Buco', 'price' => 24.99, 'description' => 'Slow-cooked veal shanks with vegetables, wine, and broth.'],
        ['name' => 'Bruschetta', 'price' => 8.99, 'description' => 'Toasted bread topped with chopped tomatoes, garlic, basil, and olive oil.'],
        ['name' => 'Tiramisu', 'price' => 7.99, 'description' => 'Classic Italian dessert made with layers of coffee-soaked ladyfingers and mascarpone cheese.'],
        ['name' => 'Caprese Salad', 'price' => 9.99, 'description' => 'Simple Italian salad with tomatoes, mozzarella cheese, basil, and olive oil.'],
        ['name' => 'Fettuccine Alfredo', 'price' => 16.99, 'description' => 'Creamy pasta dish made with fettuccine, butter, cream, and Parmesan cheese.'],
        ['name' => 'Panna Cotta', 'price' => 7.99, 'description' => 'Italian dessert made with sweetened cream thickened with gelatin and flavored with vanilla.'],
        ['name' => 'Minestrone Soup', 'price' => 9.99, 'description' => 'Hearty Italian vegetable soup made with beans, pasta, and seasonal vegetables.'],
        ['name' => 'Veal Marsala', 'price' => 22.99, 'description' => 'Tender veal cutlets cooked with mushrooms and Marsala wine sauce.'],
        ['name' => 'Cannoli', 'price' => 6.99, 'description' => 'Italian pastry filled with sweetened ricotta cheese and chocolate chips.'],
        ['name' => 'Chicken Parmesan', 'price' => 17.99, 'description' => 'Breaded chicken breast topped with marinara sauce and melted mozzarella cheese.'],
        ['name' => 'Gnocchi alla Sorrentina', 'price' => 18.99, 'description' => 'Potato dumplings baked with tomato sauce, mozzarella, and basil.'],
    ],
    'French' => [
        ['name' => 'Coq au Vin', 'price' => 18.99, 'description' => 'Classic French chicken stew cooked with wine, mushrooms, onions, and bacon.'],
        ['name' => 'Boeuf Bourguignon', 'price' => 20.99, 'description' => 'French beef stew slow-cooked with red wine, onions, and carrots.'],
        ['name' => 'Croque Monsieur', 'price' => 9.99, 'description' => 'Traditional French grilled ham and cheese sandwich topped with béchamel sauce.'],
        ['name' => 'Escargot', 'price' => 14.99, 'description' => 'Cooked snails served with garlic butter and parsley.'],
        ['name' => 'Quiche Lorraine', 'price' => 12.99, 'description' => 'Savory pie filled with bacon, cheese, and custard.'],
        ['name' => 'Duck à l\'Orange', 'price' => 23.99, 'description' => 'Roast duck served with orange sauce made from orange juice, zest, sugar, and vinegar.'],
        ['name' => 'Bouillabaisse', 'price' => 26.99, 'description' => 'Traditional French fish stew made with various types of fish, shellfish, tomatoes, and saffron.'],
        ['name' => 'Ratatouille', 'price' => 15.99, 'description' => 'Provençal vegetable stew made with tomatoes, zucchini, eggplant, onions, peppers, and herbs.'],
        ['name' => 'French Onion Soup', 'price' => 10.99, 'description' => 'Rich beef broth with caramelized onions, topped with bread and melted cheese.'],
        ['name' => 'Beef Tartare', 'price' => 19.99, 'description' => 'Raw ground beef mixed with onions, capers, Worcestershire sauce, and seasonings, often served with egg yolk.'],
        ['name' => 'Crème Brûlée', 'price' => 8.99, 'description' => 'Classic French dessert consisting of rich custard topped with caramelized sugar.'],
        ['name' => 'Salade Niçoise', 'price' => 16.99, 'description' => 'French salad with tuna, boiled eggs, tomatoes, olives, green beans, and anchovies, dressed with olive oil.'],
        ['name' => 'Foie Gras', 'price' => 29.99, 'description' => 'Rich and creamy duck or goose liver often served as a pâté or terrine.'],
        ['name' => 'Crepes Suzette', 'price' => 13.99, 'description' => 'Thin pancakes served with a sauce made from caramelized sugar, butter, orange juice, and zest, flambéed with Grand Marnier.'],
        ['name' => 'Beef Wellington', 'price' => 32.99, 'description' => 'Tender beef fillet wrapped in puff pastry with mushroom duxelles and prosciutto.'],
    ],
    'Chinese' => [
        ['name' => 'Kung Pao Chicken', 'price' => 14.99, 'description' => 'Spicy stir-fried chicken with peanuts, vegetables, and chili peppers.'],
        ['name' => 'Sweet and Sour Pork', 'price' => 12.99, 'description' => 'Crispy pork pieces coated in a tangy sweet and sour sauce with bell peppers and pineapple.'],
        ['name' => 'Beef Chow Mein', 'price' => 16.99, 'description' => 'Stir-fried noodles with beef, vegetables, and soy sauce.'],
        ['name' => 'General Tso\'s Chicken', 'price' => 15.99, 'description' => 'Deep-fried chicken pieces glazed in a sweet and spicy sauce made with soy sauce, ginger, garlic, and chili peppers.'],
        ['name' => 'Spring Rolls', 'price' => 8.99, 'description' => 'Crispy fried rolls filled with vegetables, shrimp, and sometimes meat, served with sweet and sour sauce.'],
        ['name' => 'Mapo Tofu', 'price' => 11.99, 'description' => 'Spicy Sichuan dish made with tofu, ground pork, fermented black beans, and chili peppers.'],
        ['name' => 'Dim Sum', 'price' => 17.99, 'description' => 'Assortment of bite-sized Chinese dishes served in steamer baskets, including dumplings, buns, and rolls.'],
        ['name' => 'Peking Duck', 'price' => 28.99, 'description' => 'Roast duck served with thin pancakes, scallions, and hoisin sauce.'],
        ['name' => 'Hot and Sour Soup', 'price' => 9.99, 'description' => 'Spicy and tangy soup made with tofu, bamboo shoots, mushrooms, and eggs in a vinegar and chili-based broth.'],
        ['name' => 'Chow Fun', 'price' => 14.99, 'description' => 'Stir-fried wide rice noodles with beef, bean sprouts, and onions in a soy-based sauce.'],
        ['name' => 'Ma Po Eggplant', 'price' => 13.99, 'description' => 'Sichuan dish made with eggplant, ground pork, fermented black beans, and chili peppers.'],
        ['name' => 'Szechuan Shrimp', 'price' => 18.99, 'description' => 'Spicy stir-fried shrimp with vegetables, chili peppers, and Sichuan peppercorns.'],
        ['name' => 'Orange Chicken', 'price' => 16.99, 'description' => 'Deep-fried chicken pieces coated in a tangy orange-flavored sauce.'],
        ['name' => 'Moo Shu Pork', 'price' => 15.99, 'description' => 'Stir-fried pork and vegetables wrapped in thin pancakes, served with hoisin sauce.'],
        ['name' => 'Salt and Pepper Squid', 'price' => 19.99, 'description' => 'Crispy fried squid seasoned with salt, pepper, and chili peppers, often served with dipping sauce.'],
    ],
    'Japanese' => [
        ['name' => 'Sushi', 'price' => 20.99, 'description' => 'Assortment of raw fish and seafood served on seasoned rice, often accompanied by wasabi, soy sauce, and pickled ginger.'],
        ['name' => 'Sashimi', 'price' => 22.99, 'description' => 'Thinly sliced raw fish or seafood served without rice, often accompanied by wasabi and soy sauce.'],
        ['name' => 'Ramen', 'price' => 18.99, 'description' => 'Japanese noodle soup dish made with wheat noodles, broth (usually pork or chicken-based), sliced pork, green onions, and various toppings.'],
        ['name' => 'Tempura', 'price' => 16.99, 'description' => 'Deep-fried seafood or vegetables coated in a light, crispy batter.'],
        ['name' => 'Teriyaki Chicken', 'price' => 19.99, 'description' => 'Grilled or pan-fried chicken glazed in a sweet and savory teriyaki sauce made with soy sauce, mirin, and sugar.'],
        ['name' => 'Yakitori', 'price' => 15.99, 'description' => 'Grilled skewered chicken pieces brushed with a savory sauce made with soy sauce, mirin, and sugar.'],
        ['name' => 'Udon', 'price' => 17.99, 'description' => 'Thick wheat noodles served in a hot broth, often with toppings such as tempura, tofu, or vegetables.'],
        ['name' => 'Tonkatsu', 'price' => 21.99, 'description' => 'Breaded and deep-fried pork cutlet served with shredded cabbage and tonkatsu sauce.'],
        ['name' => 'Gyoza', 'price' => 14.99, 'description' => 'Pan-fried or steamed dumplings filled with ground meat and vegetables, often served with a dipping sauce made with soy sauce and vinegar.'],
        ['name' => 'Okonomiyaki', 'price' => 18.99, 'description' => 'Japanese savory pancake made with flour, eggs, shredded cabbage, and various toppings such as pork belly, shrimp, and octopus, topped with okonomiyaki sauce, mayonnaise, and bonito flakes.'],
        ['name' => 'Chirashi', 'price' => 23.99, 'description' => 'Bowl of sushi rice topped with assorted sashimi, vegetables, and other garnishes.'],
        ['name' => 'Miso Soup', 'price' => 6.99, 'description' => 'Traditional Japanese soup made with dashi broth and fermented soybean paste (miso), often containing tofu, seaweed, and green onions.'],
        ['name' => 'Yakisoba', 'price' => 16.99, 'description' => 'Stir-fried noodles with vegetables, meat (often pork or chicken), and yakisoba sauce, similar to Worcestershire sauce.'],
        ['name' => 'Takoyaki', 'price' => 19.99, 'description' => 'Round savory balls made with a batter of wheat flour, filled with diced octopus, pickled ginger, and green onions, often topped with okonomiyaki sauce, mayonnaise, and bonito flakes.'],
        ['name' => 'Katsudon', 'price' => 20.99, 'description' => 'Japanese rice bowl dish topped with a deep-fried pork cutlet (tonkatsu), egg, and onions simmered in a sweet and savory sauce, served over rice.'],
    ],
    'Greek' => [
        ['name' => 'Moussaka', 'price' => 18.99, 'description' => 'Traditional Greek dish made with layers of eggplant, minced meat (usually lamb), tomatoes, and béchamel sauce, baked until golden brown.'],
        ['name' => 'Souvlaki', 'price' => 16.99, 'description' => 'Grilled skewers of marinated meat (often pork or chicken) served with pita bread, tzatziki sauce, and salad.'],
        ['name' => 'Spanakopita', 'price' => 14.99, 'description' => 'Greek spinach and feta cheese pie made with layers of phyllo pastry filled with a mixture of spinach, feta cheese, onions, and herbs.'],
        ['name' => 'Greek Salad', 'price' => 12.99, 'description' => 'Refreshing salad made with tomatoes, cucumbers, red onions, olives, feta cheese, and olive oil, often seasoned with oregano.'],
        ['name' => 'Dolmades', 'price' => 13.99, 'description' => 'Grape leaves stuffed with a mixture of rice, pine nuts, herbs, and sometimes minced meat, served cold as an appetizer or part of a meze platter.'],
        ['name' => 'Pastitsio', 'price' => 17.99, 'description' => 'Greek baked pasta dish similar to lasagna, made with layers of tubular pasta, minced meat (usually beef), tomato sauce, béchamel sauce, and cheese.'],
        ['name' => 'Tzatziki', 'price' => 8.99, 'description' => 'Greek yogurt and cucumber dip flavored with garlic, lemon juice, olive oil, and fresh herbs, served with pita bread or as a condiment for grilled meat.'],
        ['name' => 'Fasolada', 'price' => 11.99, 'description' => 'Traditional Greek bean soup made with white beans, tomatoes, carrots, celery, onions, and herbs, often served with crusty bread.'],
        ['name' => 'Saganaki', 'price' => 15.99, 'description' => 'Fried cheese dish made with firm cheese (such as kefalotyri or graviera), coated in flour and fried until crispy, often served with lemon wedges.'],
        ['name' => 'Baklava', 'price' => 9.99, 'description' => 'Traditional Greek dessert made with layers of phyllo pastry, chopped nuts (usually walnuts or pistachios), and honey or syrup, baked until golden and crispy.'],
        ['name' => 'Galaktoboureko', 'price' => 10.99, 'description' => 'Greek dessert made with layers of phyllo pastry and creamy semolina custard, baked until golden and then soaked in a sweet syrup flavored with lemon and orange zest.'],
        ['name' => 'Keftedes', 'price' => 13.99, 'description' => 'Greek meatballs made with a mixture of ground meat (often lamb or beef), onions, garlic, breadcrumbs, and herbs, served hot as a main course or appetizer.'],
        ['name' => 'Hummus', 'price' => 9.99, 'description' => 'Creamy dip made with mashed chickpeas, tahini, lemon juice, garlic, and olive oil, often served with pita bread or as a condiment for grilled meat.'],
        ['name' => 'Loukoumades', 'price' => 8.99, 'description' => 'Greek doughnuts made with deep-fried dough balls drizzled with honey syrup and sprinkled with cinnamon, often served hot as a dessert or snack.'],
        ['name' => 'Avgolemono Soup', 'price' => 11.99, 'description' => 'Traditional Greek soup made with chicken broth, rice or orzo pasta, lemon juice, and beaten eggs, thickened to a creamy consistency, often served hot as a comforting dish.'],
    ],
    'Spanish' => [
        ['name' => 'Paella', 'price' => 25.99, 'description' => 'Traditional Spanish rice dish cooked with saffron, seafood (such as shrimp, mussels, and squid), chicken, chorizo, and vegetables.'],
        ['name' => 'Tortilla Española', 'price' => 12.99, 'description' => 'Classic Spanish omelette made with eggs, potatoes, onions, and sometimes chorizo or other fillings, cooked until golden and firm.'],
        ['name' => 'Gazpacho', 'price' => 9.99, 'description' => 'Refreshing Spanish cold soup made with ripe tomatoes, cucumbers, bell peppers, onions, garlic, olive oil, vinegar, and bread, blended until smooth.'],
        ['name' => 'Patatas Bravas', 'price' => 10.99, 'description' => 'Spanish tapas dish made with fried potatoes served with a spicy tomato sauce (brava sauce) and aioli (garlic mayonnaise).'],
        ['name' => 'Pulpo a la Gallega', 'price' => 18.99, 'description' => 'Galician-style octopus dish made with tender boiled octopus slices served on a bed of boiled potatoes, sprinkled with paprika and olive oil.'],
        ['name' => 'Jamón Ibérico', 'price' => 30.99, 'description' => 'High-quality Spanish cured ham made from acorn-fed Iberian pigs, prized for its rich flavor and marbled texture, often served thinly sliced as a tapa or appetizer.'],
        ['name' => 'Churros con Chocolate', 'price' => 8.99, 'description' => 'Traditional Spanish dessert made with fried dough pastry strips dusted with sugar, served with thick hot chocolate dipping sauce for dipping.'],
        ['name' => 'Escalivada', 'price' => 14.99, 'description' => 'Catalan dish made with roasted vegetables (usually eggplant, bell peppers, and onions) marinated in olive oil and vinegar, served cold as an appetizer or side dish.'],
        ['name' => 'Gambas al Ajillo', 'price' => 20.99, 'description' => 'Spanish tapas dish made with shrimp sautéed in olive oil with garlic, chili peppers, and parsley, served sizzling hot.'],
        ['name' => 'Crema Catalana', 'price' => 11.99, 'description' => 'Catalan dessert similar to crème brûlée, made with a creamy custard flavored with lemon zest and cinnamon, topped with a caramelized sugar crust.'],
        ['name' => 'Sangria', 'price' => 8.99, 'description' => 'Traditional Spanish alcoholic beverage made with red wine, chopped fruit, sweetener, a splash of brandy, and a hint of spice, served chilled over ice.'],
        ['name' => 'Tortilla de Patatas', 'price' => 13.99, 'description' => 'Traditional Spanish potato omelette made with eggs, potatoes, onions, and olive oil, cooked until golden and firm, served as a tapa or light meal.'],
        ['name' => 'Boquerones en Vinagre', 'price' => 9.99, 'description' => 'Spanish tapas dish made with fresh anchovies marinated in vinegar, garlic, parsley, and olive oil, served cold as an appetizer.'],
        ['name' => 'Pa amb Tomaquet', 'price' => 7.99, 'description' => 'Catalan dish made with toasted bread rubbed with ripe tomatoes, garlic, and olive oil, often served as a side dish or snack.'],
        ['name' => 'Fabada Asturiana', 'price' => 22.99, 'description' => 'Traditional Spanish bean stew from Asturias made with white beans, chorizo, morcilla (blood sausage), pork belly, and saffron, served hot with crusty bread.'],
    ],
    'Turkey' => [
        ['name' => 'Iskender Kebab', 'price' => 22.99, 'description' => 'Turkish dish consisting of thinly sliced lamb or beef served over pieces of pide bread, topped with tomato sauce and yogurt.'],
        ['name' => 'Manti', 'price' => 18.99, 'description' => 'Turkish dumplings filled with spiced meat (usually lamb or beef), served with yogurt sauce and garlic-infused butter.'],
        ['name' => 'Adana Kebab', 'price' => 20.99, 'description' => 'Spicy Turkish kebab made with minced lamb or beef mixed with spices, shaped onto skewers, and grilled over charcoal.'],
        ['name' => 'Köfte', 'price' => 16.99, 'description' => 'Turkish meatballs made with minced meat (often lamb or beef), onions, garlic, breadcrumbs, and spices, grilled or fried and served with rice or bread.'],
        ['name' => 'Pide', 'price' => 14.99, 'description' => 'Turkish flatbread topped with various ingredients such as cheese, minced meat, vegetables, and herbs, similar to pizza.'],
        ['name' => 'Lahmacun', 'price' => 12.99, 'description' => 'Turkish thin-crust pizza topped with a spicy mixture of minced meat (usually lamb or beef), onions, tomatoes, and herbs, often served with lemon wedges and parsley.'],
        ['name' => 'Şiş Kebab', 'price' => 19.99, 'description' => 'Turkish kebab made with marinated chunks of meat (usually lamb, beef, or chicken) skewered and grilled over charcoal, served with rice, salad, and bread.'],
        ['name' => 'Menemen', 'price' => 11.99, 'description' => 'Turkish breakfast dish made with scrambled eggs cooked with tomatoes, peppers, onions, and spices, often served with bread or simit (Turkish bagel).'],
        ['name' => 'Kumpir', 'price' => 15.99, 'description' => 'Turkish baked potato dish stuffed with various toppings such as cheese, butter, olives, corn, pickles, and sausage, often served as a street food snack.'],
        ['name' => 'Simit', 'price' => 8.99, 'description' => 'Turkish circular bread encrusted with sesame seeds, often served as a popular street food snack or breakfast item, sometimes filled with cheese, tomatoes, or jam.'],
        ['name' => 'Döner Kebab', 'price' => 17.99, 'description' => 'Turkish street food made with layers of seasoned meat (usually lamb, beef, or chicken) cooked on a vertical rotisserie, sliced thinly and served in sandwiches or wraps with vegetables and sauces.'],
        ['name' => 'Turkish Delight (Lokum)', 'price' => 10.99, 'description' => 'Traditional Turkish sweet made with starch and sugar, flavored with rosewater, citrus, or other essences, often containing nuts or dried fruits and dusted with powdered sugar or coconut flakes.'],
        ['name' => 'Pilav', 'price' => 9.99, 'description' => 'Turkish rice dish made with long-grain rice cooked with butter, onions, and spices, often served as a side dish to accompany grilled meats or stews.'],
        ['name' => 'Baklava', 'price' => 13.99, 'description' => 'Traditional Turkish dessert made with layers of phyllo pastry, chopped nuts (usually pistachios or walnuts), and honey or syrup, baked until golden and crispy.'],
        ['name' => 'Kuzu Tandir', 'price' => 23.99, 'description' => 'Slow-roasted Turkish lamb dish marinated with garlic, yogurt, and spices, cooked until tender and served with rice or bread.'],
    ],
    'Thai' => [
        ['name' => 'Pad Thai', 'price' => 12.99, 'description' => 'Stir-fried rice noodles with eggs, tofu, shrimp, or chicken, flavored with tamarind sauce, fish sauce, garlic, and chili, served with lime wedges and chopped peanuts.'],
        ['name' => 'Tom Yum Goong', 'price' => 14.99, 'description' => 'Spicy and sour Thai soup made with shrimp, mushrooms, lemongrass, kaffir lime leaves, galangal, chili peppers, and lime juice, flavored with fish sauce and often topped with cilantro.'],
        ['name' => 'Green Curry', 'price' => 15.99, 'description' => 'Thai curry made with green curry paste (including green chilies, lemongrass, garlic, shallots, and spices), coconut milk, vegetables (such as bamboo shoots, bell peppers, and Thai eggplant), and choice of meat (such as chicken, beef, or shrimp).'],
        ['name' => 'Som Tum', 'price' => 10.99, 'description' => 'Spicy Thai green papaya salad made with shredded green papaya, tomatoes, green beans, peanuts, lime juice, fish sauce, garlic, and chili peppers, often served with sticky rice and grilled meat.'],
        ['name' => 'Massaman Curry', 'price' => 16.99, 'description' => 'Thai curry with Muslim origins, made with massaman curry paste (including spices such as cinnamon, cloves, and nutmeg), coconut milk, potatoes, onions, peanuts, and choice of meat (such as beef or chicken), often served with rice or roti.'],
        ['name' => 'Pad See Ew', 'price' => 13.99, 'description' => 'Stir-fried wide rice noodles with eggs, Chinese broccoli, and choice of meat (such as beef, chicken, or pork), flavored with dark soy sauce and oyster sauce, sometimes topped with crispy pork rinds.'],
        ['name' => 'Tom Kha Gai', 'price' => 11.99, 'description' => 'Thai coconut soup made with chicken, mushrooms, galangal, lemongrass, kaffir lime leaves, chili peppers, and coconut milk, flavored with fish sauce and lime juice, sometimes topped with cilantro.'],
        ['name' => 'Red Curry', 'price' => 15.99, 'description' => 'Thai curry made with red curry paste (including dried red chilies, garlic, lemongrass, shallots, and spices), coconut milk, vegetables (such as bamboo shoots, bell peppers, and Thai eggplant), and choice of meat (such as chicken, beef, or shrimp).'],
        ['name' => 'Pad Kra Pao', 'price' => 12.99, 'description' => 'Stir-fried Thai basil dish made with minced meat (such as chicken, beef, or pork), garlic, chili peppers, and holy basil leaves, flavored with soy sauce, fish sauce, and oyster sauce, served with rice and a fried egg on top.'],
        ['name' => 'Khao Pad', 'price' => 10.99, 'description' => 'Thai-style fried rice made with jasmine rice, eggs, onions, garlic, tomatoes, and choice of meat (such as shrimp, chicken, or pork), flavored with soy sauce, fish sauce, and sometimes chili paste, often served with cucumber slices and lime wedges.'],
        ['name' => 'Pad Kra Pao Moo', 'price' => 13.99, 'description' => 'Stir-fried Thai basil dish made with minced pork, garlic, chili peppers, and holy basil leaves, flavored with soy sauce, fish sauce, and oyster sauce, served with rice and a fried egg on top.'],
        ['name' => 'Yum Woon Sen', 'price' => 11.99, 'description' => 'Thai glass noodle salad made with vermicelli noodles, shrimp or chicken, onions, tomatoes, celery, cilantro, lime juice, fish sauce, and chili peppers, sometimes topped with ground peanuts.'],
        ['name' => 'Pad Prik King', 'price' => 14.99, 'description' => 'Stir-fried Thai curry dish made with green beans, bell peppers, kaffir lime leaves, and choice of meat (such as pork, chicken, or beef), flavored with prik khing curry paste (including dried red chilies, garlic, lemongrass, and spices), served with rice.'],
        ['name' => 'Gaeng Keow Wan Kai', 'price' => 16.99, 'description' => 'Thai green chicken curry made with green curry paste, coconut milk, chicken, Thai eggplant, bamboo shoots, and kaffir lime leaves, flavored with fish sauce, palm sugar, and basil leaves, served with rice.'],
        ['name' => 'Pad Thai Goong', 'price' => 15.99, 'description' => 'Stir-fried rice noodles with eggs, shrimp, tofu, bean sprouts, and green onions, flavored with tamarind sauce, fish sauce, and chili powder, served with lime wedges and chopped peanuts.'],
    ],
    'Mexican' => [
        ['name' => 'Tacos al Pastor', 'price' => 12.99, 'description' => 'Tacos filled with spit-grilled pork marinated in a combination of dried chilies, spices, and pineapple, served with onions, cilantro, and salsa.'],
        ['name' => 'Guacamole', 'price' => 9.99, 'description' => 'Traditional Mexican dip made with mashed avocados, lime juice, onions, tomatoes, cilantro, and jalapeños, often served with tortilla chips or as a topping for tacos and burritos.'],
        ['name' => 'Enchiladas', 'price' => 14.99, 'description' => 'Corn tortillas rolled around a filling (such as cheese, meat, or beans), covered with chili sauce (such as red or green salsa) and cheese, baked until heated through, and served with rice and beans.'],
        ['name' => 'Tamales', 'price' => 10.99, 'description' => 'Traditional Mexican dish made with masa (corn dough) filled with a savory or sweet filling (such as pork, chicken, beans, cheese, or fruit), wrapped in corn husks or banana leaves, and steamed until cooked through.'],
        ['name' => 'Chiles Rellenos', 'price' => 15.99, 'description' => 'Poblano peppers stuffed with cheese, meat (such as ground beef or shredded chicken), or beans, dipped in egg batter, fried until golden and crispy, and served with tomato sauce or salsa.'],
        ['name' => 'Pozole', 'price' => 11.99, 'description' => 'Traditional Mexican soup made with hominy (dried corn kernels), pork or chicken, chili peppers, garlic, onions, and spices, garnished with shredded cabbage, radishes, avocado, lime, and dried oregano.'],
        ['name' => 'Chilaquiles', 'price' => 13.99, 'description' => 'Traditional Mexican breakfast dish made with fried tortilla chips simmered in salsa (red or green), topped with cheese, sour cream, avocado, and sometimes eggs or shredded chicken, served with refried beans.'],
        ['name' => 'Ceviche', 'price' => 16.99, 'description' => 'Traditional Mexican seafood dish made with raw fish (such as shrimp, scallops, or white fish) marinated in citrus juices (such as lime or lemon), mixed with onions, tomatoes, cilantro, chili peppers, and avocado, served chilled with tortilla chips or tostadas.'],
        ['name' => 'Mole', 'price' => 17.99, 'description' => 'Traditional Mexican sauce made with a combination of chili peppers, chocolate, spices, nuts, and sometimes fruit, used as a marinade or sauce for meats (such as chicken or turkey) or enchiladas, often served with rice and tortillas.'],
        ['name' => 'Burritos', 'price' => 14.99, 'description' => 'Large flour tortillas filled with a combination of ingredients (such as rice, beans, meat, cheese, and salsa), rolled up into a cylindrical shape, and grilled or toasted until warm and crispy, often served with guacamole and sour cream.'],
        ['name' => 'Tostadas', 'price' => 10.99, 'description' => 'Crispy fried or toasted corn tortillas topped with refried beans, shredded lettuce, diced tomatoes, cheese, salsa, and choice of meat (such as shredded chicken, beef, or pork), sometimes garnished with sour cream, guacamole, or pickled jalapeños.'],
        ['name' => 'Sopes', 'price' => 12.99, 'description' => 'Thick corn tortillas topped with refried beans, shredded meat (such as beef, chicken, or pork), lettuce, cheese, salsa, and sometimes sour cream or guacamole, served as an appetizer or snack.'],
        ['name' => 'Churros', 'price' => 8.99, 'description' => 'Traditional Mexican dessert made with fried dough pastry (choux pastry) rolled in cinnamon sugar, often served hot with chocolate sauce or dulce de leche for dipping.'],
        ['name' => 'Carne Asada', 'price' => 18.99, 'description' => 'Grilled marinated beef (such as skirt steak or flank steak), served sliced with grilled onions, bell peppers, and tortillas for making tacos or burritos, often accompanied by salsa, guacamole, and refried beans.'],
        ['name' => 'Tortilla Soup', 'price' => 11.99, 'description' => 'Traditional Mexican soup made with chicken broth, tomatoes, onions, garlic, chili peppers, and tortilla strips, garnished with avocado, cheese, cilantro, and lime wedges, sometimes topped with crispy tortilla strips or fried tortilla chips.'],
    ],
    'American' => [
        ['name' => 'Hamburger', 'price' => 10.99, 'description' => 'Grilled beef patty served on a bun with lettuce, tomato, onion, pickles, and condiments such as ketchup and mustard.'],
        ['name' => 'Cheeseburger', 'price' => 12.99, 'description' => 'Hamburger topped with melted cheese, served on a bun with lettuce, tomato, onion, pickles, and condiments.'],
        ['name' => 'Fried Chicken', 'price' => 14.99, 'description' => 'Chicken pieces (such as drumsticks, thighs, or breast) coated in seasoned flour or breadcrumbs, deep-fried until golden and crispy.'],
        ['name' => 'BBQ Ribs', 'price' => 16.99, 'description' => 'Pork ribs slow-cooked or smoked until tender, then grilled and basted with barbecue sauce, served with coleslaw and cornbread.'],
        ['name' => 'Macaroni and Cheese', 'price' => 11.99, 'description' => 'Pasta (such as macaroni) cooked in a creamy cheese sauce made with cheddar, mozzarella, or other cheese varieties, sometimes topped with breadcrumbs and baked until bubbly and golden.'],
        ['name' => 'Buffalo Wings', 'price' => 13.99, 'description' => 'Chicken wings deep-fried until crispy, then tossed in a spicy buffalo sauce made with hot sauce, butter, and other seasonings, served with celery sticks and blue cheese dressing.'],
        ['name' => 'Steak', 'price' => 19.99, 'description' => 'Beef steak (such as ribeye, sirloin, or filet mignon) grilled or pan-seared to the desired doneness, served with a side of vegetables and choice of potato (such as mashed, baked, or fries).'],
        ['name' => 'Apple Pie', 'price' => 8.99, 'description' => 'Traditional American dessert made with a flaky pie crust filled with sliced apples, sugar, cinnamon, and sometimes other spices, baked until the apples are tender and the crust is golden brown.'],
        ['name' => 'Pancakes', 'price' => 9.99, 'description' => 'Fluffy pancakes made with a batter of flour, eggs, milk, and baking powder, cooked on a griddle until golden brown, served with butter and maple syrup.'],
        ['name' => 'Clam Chowder', 'price' => 12.99, 'description' => 'Creamy soup made with clams, potatoes, onions, celery, and sometimes bacon, flavored with herbs and spices, served with oyster crackers or crusty bread.'],
        ['name' => 'Hot Dog', 'price' => 7.99, 'description' => 'Grilled or steamed sausage (such as frankfurter or bratwurst) served in a sliced bun, topped with mustard, ketchup, relish, onions, sauerkraut, or other condiments.'],
        ['name' => 'Grilled Cheese Sandwich', 'price' => 9.99, 'description' => 'Sandwich made with slices of cheese (such as cheddar or American) between buttered bread slices, grilled or toasted until the cheese is melted and the bread is golden brown.'],
        ['name' => 'Cornbread', 'price' => 6.99, 'description' => 'Bread made with cornmeal, flour, eggs, milk, and sometimes sugar or honey, baked until golden brown and served warm with butter.'],
        ['name' => 'Chocolate Chip Cookies', 'price' => 8.99, 'description' => 'Classic American cookies made with a dough of flour, sugar, butter, eggs, vanilla extract, and chocolate chips, baked until golden brown and chewy.'],
        ['name' => 'Caesar Salad', 'price' => 10.99, 'description' => 'Salad made with romaine lettuce, croutons, Parmesan cheese, and Caesar dressing (made with anchovies, garlic, Dijon mustard, lemon juice, olive oil, and egg yolks), sometimes topped with grilled chicken or shrimp.'],
    ],
];